name: laravel lib ci dev

on:
  workflow_call:
    secrets:
      SATIS_URL:
        required: true
      SATIS_USERNAME:
        required: true
      SATIS_PASSWORD:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      FORGE_SATIS_WEBHOOK_URL:
        required: true
      SETASIGN_USERNAME:
        required: false
      SETASIGN_PASSWORD:
        required: false

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ "8.1" ]
        laravel: [ 9.* ]
        include:
          - laravel: 9.*
            testbench: ^7.4

    name: PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ runner.os }}-${{ matrix.laravel }}-testbench-${{ matrix.testbench }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, sqlsrv, pdo_sqlsrv

      # We need to double-escape the password string on Windows, since the new token format contains a pipe character
      # that wasn't playing well with PowerShell. The double quotes are unpacked correctly down the line, so the
      # resulting config in auth.json is valid

      - name: 'Authenticate SelbySatis (Windows)'
        if: runner.os == 'Windows'
        run: composer config --global http-basic.${{secrets.SATIS_URL}} "${{secrets.SATIS_USERNAME}}" '"${{secrets.SATIS_PASSWORD}}"'

      - name: 'Authenticate SelbySatis'
        if: runner.os != 'Windows'
        run: composer config --global http-basic.${{secrets.SATIS_URL}} "${{secrets.SATIS_USERNAME}}" "${{secrets.SATIS_PASSWORD}}"

      - name: 'Authenticate Setasign'
        env:
          SETASIGN_USERNAME: ${{ secrets.SETASIGN_USERNAME }}
        if: "${{ env.SETASIGN_USERNAME != '' }}"
        run: composer config --global http-basic.www.setasign.com "${{secrets.SETASIGN_USERNAME}}" "${{secrets.SETASIGN_PASSWORD}}"

      - name: Install OS dependencies
        run: sudo apt-get update && sudo apt-get install -y poppler-utils chromium-browser imagemagick

      - name: Install npm packages
        run: npm install

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: |
            composer require "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
            composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
            composer update --prefer-dist --no-interaction

      - name: Detect installed Laravel version
        id: laravel_version
        run: |
          echo "::set-output name=LARAVEL_VERSION::$(echo "$(echo "$(composer show laravel/framework | grep versions | grep -Eow 'v[0-9]+' | sed 's/v//').*")")"
          echo "Installed version $(echo "$(echo "$(composer show laravel/framework | grep versions | grep -Eow 'v[0-9]+' | sed 's/v//').*")") / Expected version ${{ matrix.laravel }}"

      - name: Fail on incorrect Laravel version
        if: steps.laravel_version.outputs.LARAVEL_VERSION != matrix.laravel
        run: echo '::error::Incorrect Laravel version installed (${{ steps.laravel_version.outputs.LARAVEL_VERSION }})' && exit 1

      - name: Run test suite
        run: composer run-script test

      - name: Send Slack failure notification
        uses: act10ns/slack@v1.2.2
        if: failure()
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
